# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: conf.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='conf.proto',
  package='pml.msg',
  syntax='proto2',
  serialized_options=b'\n\017com.pdd.pml.msgP\001',
  serialized_pb=b'\n\nconf.proto\x12\x07pml.msg\"\x99\x03\n\x0b\x46\x65\x61tureConf\x12-\n\x07\x66\x65\x61ture\x18\x01 \x03(\x0b\x32\x1c.pml.msg.FeatureConf.Feature\x12(\n\x03\x64\x65\x66\x18\x02 \x03(\x0b\x32\x1b.pml.msg.FeatureConf.Define\x12*\n\x03seq\x18\x03 \x01(\x0b\x32\x1d.pml.msg.FeatureConf.Sequence\x12\x0f\n\x07include\x18\x04 \x03(\t\x1a\x32\n\x06\x44\x65\x66ine\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\n\n\x02op\x18\x02 \x02(\t\x12\x0e\n\x06params\x18\x03 \x01(\t\x1aw\n\x07\x46\x65\x61ture\x12\x0b\n\x03tag\x18\x01 \x03(\x05\x12\x0b\n\x03\x64\x65\x66\x18\x02 \x01(\t\x12\x11\n\tprojector\x18\x03 \x03(\t\x12\x18\n\x10setup_properties\x18\x04 \x01(\t\x12\r\n\x05\x64icts\x18\x05 \x01(\t\x12\x16\n\x0e\x64\x65\x66\x61ult_values\x18\x06 \x01(\t\x1aG\n\x08Sequence\x12\x0c\n\x04name\x18\x01 \x02(\t\x12-\n\x07\x66\x65\x61ture\x18\x02 \x03(\x0b\x32\x1c.pml.msg.FeatureConf.Feature\"C\n\x0ePredictService\x12\x0b\n\x03tag\x18\x01 \x03(\x05\x12$\n\x1cinput_feature_generator_name\x18\x02 \x02(\t\"\xa0\x02\n\x0e\x46\x65\x61tureService\x12*\n\x04type\x18\x01 \x02(\x0e\x32\x1c.pml.msg.FeatureService.Type\x12%\n\x1d\x44\x45PRECATED_naming_service_uri\x18\x02 \x01(\t\x12\x30\n\x0fpredict_service\x18\x03 \x01(\x0b\x32\x17.pml.msg.PredictService\x12\x1b\n\x13rpc_call_identifier\x18\x04 \x01(\t\"l\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x13\n\x0fPREDICT_SERVICE\x10\x01\x12\x0e\n\nTF_SERVICE\x10\x02\x12\x18\n\x14\x43ONTEXT_ONLY_SERVICE\x10\x03\x12\x18\n\x14\x44OCUMENT_RAW_SERVICE\x10\x04\x42\x13\n\x0f\x63om.pdd.pml.msgP\x01'
)



_FEATURESERVICE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='pml.msg.FeatureService.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PREDICT_SERVICE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TF_SERVICE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONTEXT_ONLY_SERVICE', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DOCUMENT_RAW_SERVICE', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=685,
  serialized_end=793,
)
_sym_db.RegisterEnumDescriptor(_FEATURESERVICE_TYPE)


_FEATURECONF_DEFINE = _descriptor.Descriptor(
  name='Define',
  full_name='pml.msg.FeatureConf.Define',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='pml.msg.FeatureConf.Define.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='op', full_name='pml.msg.FeatureConf.Define.op', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='params', full_name='pml.msg.FeatureConf.Define.params', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=239,
)

_FEATURECONF_FEATURE = _descriptor.Descriptor(
  name='Feature',
  full_name='pml.msg.FeatureConf.Feature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tag', full_name='pml.msg.FeatureConf.Feature.tag', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='def', full_name='pml.msg.FeatureConf.Feature.def', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='projector', full_name='pml.msg.FeatureConf.Feature.projector', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='setup_properties', full_name='pml.msg.FeatureConf.Feature.setup_properties', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dicts', full_name='pml.msg.FeatureConf.Feature.dicts', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='default_values', full_name='pml.msg.FeatureConf.Feature.default_values', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=241,
  serialized_end=360,
)

_FEATURECONF_SEQUENCE = _descriptor.Descriptor(
  name='Sequence',
  full_name='pml.msg.FeatureConf.Sequence',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='pml.msg.FeatureConf.Sequence.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='feature', full_name='pml.msg.FeatureConf.Sequence.feature', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=362,
  serialized_end=433,
)

_FEATURECONF = _descriptor.Descriptor(
  name='FeatureConf',
  full_name='pml.msg.FeatureConf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='feature', full_name='pml.msg.FeatureConf.feature', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='def', full_name='pml.msg.FeatureConf.def', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seq', full_name='pml.msg.FeatureConf.seq', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='include', full_name='pml.msg.FeatureConf.include', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_FEATURECONF_DEFINE, _FEATURECONF_FEATURE, _FEATURECONF_SEQUENCE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=433,
)


_PREDICTSERVICE = _descriptor.Descriptor(
  name='PredictService',
  full_name='pml.msg.PredictService',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tag', full_name='pml.msg.PredictService.tag', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='input_feature_generator_name', full_name='pml.msg.PredictService.input_feature_generator_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=435,
  serialized_end=502,
)


_FEATURESERVICE = _descriptor.Descriptor(
  name='FeatureService',
  full_name='pml.msg.FeatureService',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='pml.msg.FeatureService.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='DEPRECATED_naming_service_uri', full_name='pml.msg.FeatureService.DEPRECATED_naming_service_uri', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='predict_service', full_name='pml.msg.FeatureService.predict_service', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rpc_call_identifier', full_name='pml.msg.FeatureService.rpc_call_identifier', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FEATURESERVICE_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=505,
  serialized_end=793,
)

_FEATURECONF_DEFINE.containing_type = _FEATURECONF
_FEATURECONF_FEATURE.containing_type = _FEATURECONF
_FEATURECONF_SEQUENCE.fields_by_name['feature'].message_type = _FEATURECONF_FEATURE
_FEATURECONF_SEQUENCE.containing_type = _FEATURECONF
_FEATURECONF.fields_by_name['feature'].message_type = _FEATURECONF_FEATURE
_FEATURECONF.fields_by_name['def'].message_type = _FEATURECONF_DEFINE
_FEATURECONF.fields_by_name['seq'].message_type = _FEATURECONF_SEQUENCE
_FEATURESERVICE.fields_by_name['type'].enum_type = _FEATURESERVICE_TYPE
_FEATURESERVICE.fields_by_name['predict_service'].message_type = _PREDICTSERVICE
_FEATURESERVICE_TYPE.containing_type = _FEATURESERVICE
DESCRIPTOR.message_types_by_name['FeatureConf'] = _FEATURECONF
DESCRIPTOR.message_types_by_name['PredictService'] = _PREDICTSERVICE
DESCRIPTOR.message_types_by_name['FeatureService'] = _FEATURESERVICE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FeatureConf = _reflection.GeneratedProtocolMessageType('FeatureConf', (_message.Message,), {

  'Define' : _reflection.GeneratedProtocolMessageType('Define', (_message.Message,), {
    'DESCRIPTOR' : _FEATURECONF_DEFINE,
    '__module__' : 'conf_pb2'
    # @@protoc_insertion_point(class_scope:pml.msg.FeatureConf.Define)
    })
  ,

  'Feature' : _reflection.GeneratedProtocolMessageType('Feature', (_message.Message,), {
    'DESCRIPTOR' : _FEATURECONF_FEATURE,
    '__module__' : 'conf_pb2'
    # @@protoc_insertion_point(class_scope:pml.msg.FeatureConf.Feature)
    })
  ,

  'Sequence' : _reflection.GeneratedProtocolMessageType('Sequence', (_message.Message,), {
    'DESCRIPTOR' : _FEATURECONF_SEQUENCE,
    '__module__' : 'conf_pb2'
    # @@protoc_insertion_point(class_scope:pml.msg.FeatureConf.Sequence)
    })
  ,
  'DESCRIPTOR' : _FEATURECONF,
  '__module__' : 'conf_pb2'
  # @@protoc_insertion_point(class_scope:pml.msg.FeatureConf)
  })
_sym_db.RegisterMessage(FeatureConf)
_sym_db.RegisterMessage(FeatureConf.Define)
_sym_db.RegisterMessage(FeatureConf.Feature)
_sym_db.RegisterMessage(FeatureConf.Sequence)

PredictService = _reflection.GeneratedProtocolMessageType('PredictService', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTSERVICE,
  '__module__' : 'conf_pb2'
  # @@protoc_insertion_point(class_scope:pml.msg.PredictService)
  })
_sym_db.RegisterMessage(PredictService)

FeatureService = _reflection.GeneratedProtocolMessageType('FeatureService', (_message.Message,), {
  'DESCRIPTOR' : _FEATURESERVICE,
  '__module__' : 'conf_pb2'
  # @@protoc_insertion_point(class_scope:pml.msg.FeatureService)
  })
_sym_db.RegisterMessage(FeatureService)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
