working_dir: "hdfs://yiran-data-ns/user/search/rank_data/tieqiu/ckpts/inet_v5_cnn_sumpool"

train_and_eval:
    training_path: "hdfs://yiran-data-ns/user/search/rank_data/moning/polaris_streaming/ctr/201906\\{1[6-9],2[0-5]\\}"
    eval_path: "hdfs://yiran-data-ns/user/search/rank_data/moning/polaris_streaming/ctr/20190627"
    graph_path: "hdfs://yiran-data-ns/user/search/rank_data/tieqiu/graphs/inet_v5_cnn_sumpool"
    op_info_path: "hdfs://yiran-data-ns/user/search/rank_data/tieqiu/graphs/inet_v5_cnn_sumpool_op_list"

export:
    graph_path: "hdfs://yiran-data-ns/user/search/rank_data/tieqiu/graphs/inet_train_v5_cnn_sumpool_exp_b200"
    serving_sig_path: "hdfs://yiran-data-ns/user/search/rank_data/tieqiu/graphs/inet_serving_graph_v5_exp_serving_sig"
    done_file_path:  "hdfs://yiran-data-ns/user/search/rank_data/tieqiu/saved_models/inet_graph_train_v5_exp/done_list"
    saved_model_dir: "hdfs://yiran-data-ns/user/search/rank_data/tieqiu/saved_models/inet_graph_train_v5_exp"

daily:
    daily_train_path: "hdfs://yiran-data-ns/user/search/rank_data/moning/polaris_streaming/ctr/{:%Y-%m-%d}"
