# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vector.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vector.proto',
  package='yyj.msg',
  syntax='proto2',
  serialized_options=b'\n\017com.pdd.yyj.msgP\001',
  serialized_pb=b'\n\x0cvector.proto\x12\x07yyj.msg\"(\n\rVectorFeature\x12\n\n\x02pk\x18\x01 \x02(\x03\x12\x0b\n\x03vec\x18\x02 \x03(\x02\x42\x13\n\x0f\x63om.pdd.yyj.msgP\x01'
)




_VECTORFEATURE = _descriptor.Descriptor(
  name='VectorFeature',
  full_name='yyj.msg.VectorFeature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pk', full_name='yyj.msg.VectorFeature.pk', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vec', full_name='yyj.msg.VectorFeature.vec', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=65,
)

DESCRIPTOR.message_types_by_name['VectorFeature'] = _VECTORFEATURE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VectorFeature = _reflection.GeneratedProtocolMessageType('VectorFeature', (_message.Message,), {
  'DESCRIPTOR' : _VECTORFEATURE,
  '__module__' : 'vector_pb2'
  # @@protoc_insertion_point(class_scope:yyj.msg.VectorFeature)
  })
_sym_db.RegisterMessage(VectorFeature)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
